apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minio.danmanners.io
    kubernetes.io/ingress.class: traefik
  labels:
    app: minio
  name: gitlab-minio-traefik
  namespace: default
spec:
  rules:
    - host: minio.danmanners.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: gitlab-minio-svc
              servicePort: 9000
