apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: registry.danmanners.io
    kubernetes.io/ingress.class: traefik
  labels:
    app: registry
  name: gitlab-registry-traefik
  namespace: default
spec:
  rules:
    - host: registry.danmanners.io
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: gitlab-registry
              servicePort: 5000
